image: gcr.io/kaniko-project/executor:latest
stages: [build, deploy]
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/chat-exporter:$CI_COMMIT_SHORT_SHA
build:
  stage: build
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile \
      --destination $IMAGE_TAG --destination $CI_REGISTRY_IMAGE/chat-exporter:latest
  tags: [kaniko]
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script: ["kubectl", "apply", "-f", "k8s/"] 
  environment: { name: production }
  only: [main]
