apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-chat-secrets
  namespace: chat-automation
spec:
  provider: vault
  parameters:
    vaultAddress: https://vault.example.com:8200
    roleName: chat-exporter-role
    objects: |
      - secretPath: secret/data/chat-tokens
        objectName: chatgptToken
        secretKey: chatgpt-token
      - secretPath: secret/data/chat-tokens
        objectName: claudeToken
        secretKey: claude-token
  secretObjects:
  - secretName: chat-tokens
    type: Opaque
    data:
    - key: chatgpt-token
      objectName: chatgptToken
    - key: claude-token
      objectName: claudeToken
